import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { styleText } from "util";
import ContextProvider from "@/context/ContextProvider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   
     
      <body >
      <ContextProvider >
      <Navbar/>
      </ContextProvider> 
        {children}</body>
    </html>
  );
}
